#!/usr/bin/python3
import socket
import telnetlib

h="192.168.57.68"
p=2003

s=socket.socket(socket.AF_INET,socket.SOCK_STREAM)
s.connect((h,p))

t=telnetlib.Telnet()
t.sock=s
t.interact()

s.close()

Save it as:
